language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install bandit safety
script: 
  - bandit -f json -o sast-result.json app.py
  - safety check -r requirements.txt --json > sca-result.json
addons:
  artifacts:
    paths:
      - sast-result.json 
      - sca-result.json